{
 "title": "Nezha",
 "description": "nezha-exporter dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "label": "作业", "query": "nezhav1" },
   {
    "name": "group",
    "label": "分组",
    "query": {
     "query": "label_values({job=\"$job\"},group)"
    }
   },
   {
    "name": "name",
    "label": "名称",
    "query": {
     "query": "label_values({job=\"$job\", group=~\"$group\"},name)"
    }
   },
   { "name": "avg_over_time", "label": "动态平均", "query": "1m,5m,1h,1d,10s" }
  ]
 },
 "panels": [
  { "title": "服务器状态", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "最新数据",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max by(name) (nezha_cpu{job=\"$job\", group=~\"$group\", name=~\"$name\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "(\r\n  max by(name) (nezha_mem_used{job=\"$job\", group=~\"$group\", name=~\"$name\"})\r\n  /\r\n  max by(name) (nezha_mem_total{job=\"$job\", group=~\"$group\", name=~\"$name\"})\r\n)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "(\r\nmax by(name) (nezha_disk_used{job=\"$job\", group=~\"$group\", name=~\"$name\"})\r\n/\r\nmax by(name) (nezha_disk_total{job=\"$job\", group=~\"$group\", name=~\"$name\"})\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(name) (nezha_net_in_speed{job=\"$job\", group=~\"$group\", name=~\"$name\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(name) (nezha_net_out_speed{job=\"$job\", group=~\"$group\", name=~\"$name\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(name) (nezha_net_in_transfer{job=\"$job\", group=~\"$group\", name=~\"$name\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(name) (nezha_net_out_transfer{job=\"$job\", group=~\"$group\", name=~\"$name\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(name) (nezha_process_count{job=\"$job\", group=~\"$group\", name=~\"$name\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(name) (nezha_tcp_conn_count{job=\"$job\", group=~\"$group\", name=~\"$name\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(name) (nezha_udp_conn_count{job=\"$job\", group=~\"$group\", name=~\"$name\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "(\r\n  max by(name) (nezha_swap_used{job=\"$job\", group=~\"$group\", name=~\"$name\"})\r\n  /\r\n  max by(name) (nezha_swap_total{job=\"$job\", group=~\"$group\", name=~\"$name\"})\r\n)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(name) (nezha_uptime{job=\"$job\", group=~\"$group\", name=~\"$name\"})\r\n\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max by(name) (avg_over_time(nezha_cpu{job=\"$job\", group=~\"$group\", name=~\"$name\"}[$avg_over_time]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\r\n  max by(name) (avg_over_time(nezha_mem_used{job=\"$job\", group=~\"$group\", name=~\"$name\"}[$avg_over_time]))\r\n  /\r\n  max by(name) (avg_over_time(nezha_mem_total{job=\"$job\", group=~\"$group\", name=~\"$name\"}[$avg_over_time]))\r\n)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "交换空间",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\r\n  max by(name) (avg_over_time(nezha_swap_used{job=\"$job\", group=~\"$group\", name=~\"$name\"}[$avg_over_time]))\r\n  /\r\n  max by(name) (avg_over_time(nezha_swap_total{job=\"$job\", group=~\"$group\", name=~\"$name\"}[$avg_over_time]))\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "进程数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by(name) (avg_over_time(nezha_process_count{job=\"$job\", group=~\"$group\", name=~\"$name\"}[$avg_over_time]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "上传+下载网速",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (max by(name)(avg_over_time(nezha_net_in_speed{job=\"$job\", group=~\"$group\", name=~\"$name\"}[$avg_over_time])))",
     "legendFormat": "总下载"
    },
    {
     "expr": "sum (max by(name)(avg_over_time(nezha_net_out_speed{job=\"$job\", group=~\"$group\", name=~\"$name\"}[$avg_over_time])))\r\n",
     "legendFormat": "总上传"
    }
   ]
  },
  {
   "title": "上传+下载网速",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "(\r\n  max by(name) (avg_over_time(nezha_net_in_speed{job=\"$job\", group=~\"$group\", name=~\"$name\"}[$avg_over_time]))\r\n  +\r\n  max by(name) (avg_over_time(nezha_net_out_speed{job=\"$job\", group=~\"$group\", name=~\"$name\"}[$avg_over_time]))\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TCP连接数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by(name) (avg_over_time(nezha_tcp_conn_count{job=\"$job\", group=~\"$group\", name=~\"$name\"}[$avg_over_time]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UDP连接数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by(name) (avg_over_time(nezha_udp_conn_count{job=\"$job\", group=~\"$group\", name=~\"$name\"}[$avg_over_time]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "磁盘使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\r\nmax by(name) (avg_over_time(nezha_disk_used{job=\"$job\", group=~\"$group\", name=~\"$name\"}[$avg_over_time]))\r\n/\r\nmax by(name) (avg_over_time(nezha_disk_total{job=\"$job\", group=~\"$group\", name=~\"$name\"}[$avg_over_time]))\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "运行时长",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(name) (nezha_uptime{job=\"$job\", group=~\"$group\", name=~\"$name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "温度",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg_over_time(nezha_temperature{job=\"$job\", group=~\"$group\", name=~\"$name\"}[$avg_over_time])",
     "legendFormat": "{{name}}_[{{temp_name}}]"
    }
   ]
  },
  { "title": "网络", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "$name 监控服务",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "repeat": "name",
   "targets": [
    {
     "expr": "max by(monitor_name) (avg_over_time(nezha_service_avg_delay_ms{job=\"$job\", group=~\"$group\", name=~\"$name\"}[$avg_over_time]))",
     "legendFormat": "{{monitor_name}}"
    }
   ]
  }
 ]
}